### ISSUE TITLE
diagnosticls and eslint

### ISSUE THREAD

**Issue by casperstorm** [rockerBOO/dotfiles#2]
Hi Rockerboo.
I've been following your dotfiles since you are using prettier, eslint and TS with nvim-lsp, something I've recently tried to migrate to (from coc). I have been following https://github.com/neovim/neovim/pull/12655 to have multiple LSP running. I tried to [copy your setup](https://github.com/rockerBOO/dotfiles/blob/master/config/nvim/lua/lsp_config.lua). This is what i currently have: [lsp/init.lua](https://github.com/casperstorm/dotfiles/blob/feat/diagnostic-transition/states/nvim/files/lua/lsp/init.lua).

My problem is that eslint is not showing up. TS LSP is running and working but unsure what I need to do in order for eslint to  work. Do you have any suggestions?

If you don't want these questions then I respect if you close this issue.

**Comment by rockerBOO** [comment]
My version is kinda hacky in that it runs `yarn eslint` which uses the package eslint version. So change the `yarn eslint` to `eslint` and install eslint globally. 

This is where I got the code from initially: https://www.reddit.com/r/neovim/comments/j2tn38/help_with_integrate_nvimlsp_with_eslint/g79ekv5/

**Comment by rockerBOO** [comment]
Also to note, I sort of dropped it in, to allow me to try it without ALE. There is a bit of polish I would do even initially (tsserver and eslint duplicate simular rules, maybe disabling hints from typescript-language-server)

But this way I can go through diagnostics all in the same interface, get virtual text and so on.

**Comment by casperstorm** [comment]
I'll try your suggestion, thanks.

I like it is close to being optimal, but it still feels like a uphill battle to get it running as smoothly as VSCode runs TS with ESLint and Prettier. I've had a pretty good CoC setup for a long time but it just slows my machine down so much. I'll get there eventually. I just thought that this new PR with multiple LSP's was the missing pieces!

It seems you just need to disable hints (errors) from TS LSP, I guess you want those errors/warnings from ESLint based of your project config. It could vary.

**Comment by rockerBOO** [comment]
I would say you can directly blame VSCode/Typescript being the same vendor. We must push against this force though so we can get the support we want. There are various implementation with people not wanting to maintian their typescript language servers. So its more rough because the main vendor has built most of the typescript language server directly into VSCode. CoC has a lot of the same limitations of the typescript LS but it integrates linter/formatting support (i'm sort of guessing, never actually used CoC). 

IIRC there may be a proper typescript language server by Microsoft in the future. I'd imagine it would come with yarn/package.json support to detect if you have eslintrc or prettierrc and automatically run it those as well.

So for now I'm just going to try and get diagnosticls to work well with the gaps missing and not try to overlap.

**Comment by rockerBOO** [comment]
See https://github.com/microsoft/TypeScript/issues/39459 for info about the Microsoft TS LS

**Comment by casperstorm** [comment]
I just tried to spend some more time with it. I am obviously making some kind of mistake, because no matter what I do eslint warnings or errors are not showing. In my head I would love them to show inline like the default lsp errors, but not sure what I need to change, i feel i have similar setup as you do.

Do you wanna take a quick look? I admit I am not the best at the config setup.
Here is the important files:

* [Plugins section with LSP](https://github.com/casperstorm/dotfiles/blob/feat/diagnostic-transition/states/nvim/files/plugins.vim#L46-L56)
* [Source the lua code from init.vim](https://github.com/casperstorm/dotfiles/blob/feat/diagnostic-transition/states/nvim/files/init.vim#L103-L105) 
* [LSP lua settings](https://github.com/casperstorm/dotfiles/blob/feat/diagnostic-transition/states/nvim/files/lua/lsp/init.lua)
* [Completion settings](https://github.com/casperstorm/dotfiles/blob/feat/diagnostic-transition/states/nvim/files/plugins/completion.vim)

> So its more rough because the main vendor has built most of the typescript language server directly into VSCode.

This sucks, will take a while to get us up to speed, but I agree we must truck on. I did try VSCode with Vim extension but while I love the integration with TS (and Rust, which is the two languages i use professionally) I can't leave my "native" (N)vim.

**Comment by rockerBOO** [comment]
I'm going to take a look a little later tonight. I had it working but now its not working so I'm going to figure out all the eslint/prettier things.

**Comment by rockerBOO** [comment]
Ok I currently have diagnosticls linting and formatting, and tsserver also doing it's things.

![2020-11-17-013545_4480x1440_scrot](https://user-images.githubusercontent.com/15027/99355182-d4b74f80-2875-11eb-8962-04c9927e9293.png)


The issue was the `filetypes` list needed `typescript.tsx` which has is from https://github.com/peitalin/vim-jsx-typescript

https://github.com/rockerBOO/dotfiles/blob/master/config/nvim/lua/lsp_config.lua Its mostly the same. 

I added an on attach hook for doing the formatting. https://www.reddit.com/r/neovim/comments/jvisg5/lets_talk_formatting_again/ gave the example I am using.

**Comment by casperstorm** [comment]
This is great nice. I just got it to work as well. Thanks for posting this to me as well.
Excited to see the development of the whole TS LSP server going forward.

**Comment by rockerBOO** [comment]
For others following along, I have moved to using `efm-langserver` instead of `diagnosticls`  but still should work. The config is in .config/efm-langserver/config.yaml instead of directly in the lsp config.

**Comment by dagadbm** [comment]
any  reasoning why? is it more performing?

I also have a question,  why dont we have an lsp manager plugin to handle all these custom configurations?
I see lspinstall but it stops at efm/diagnosticls and not really support for all the linting/formatting  ecosystem..

i dont have the skillls to do this but I was wondering why no one hasnt thought about this before

**Comment by rockerBOO** [comment]
Honestly I was just lazy and efm had a configuration already written on their README. Not sure of the absolute differences (speed, size, updating, toolchain) but it worked more for me. 

LSP is pretty new, especially for neovim (isn't even released yet) so "feature-full" plugins will come a little later. Likely packages that will automatically setup specific environments (like typescript + eslint + prettier) will come more in the future. Other languages like rust/go have an inclusive toolchain that everyone uses (rust-analyzer, rustfmt, clippy) (go fmt, go vet) so these are a little easier to have all working with 1 LS.

With the release of neovim 0.5 it will be more likely to have things more mature, without all the growing pains of missing utility. I have a [list of the newer neovim plugins for LSP ](https://github.com/rockerBOO/awesome-neovim#lsp) which is growing as the LSP client implementation is getting ready for release.

**Comment by dagadbm** [comment]
i *might* have jumped to soon on the bandwagon because now every time i
open a file on my vimrc i  get an error i never saw before:

Error detected whiile processing function<SNR>28_UseConfigFiles:
line 40:
E714: list required

But yes I understand now the  dificulty of this. It also doesnt help that
microsoft being  all friendly open  source kindly  neglets actually
implementing the LSP part of the language they created ...

**Comment by dagadbm** [comment]
Aparently its  from editorconfig-vim. Had to  uninstall  it
